version: "3.9"
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "80:80"
    depends_on: 
    - "redis"
    volumes:
      - ./app:/app
  redis:
    image: "redis:6.0.9"
    ports:
      - "6379:6379"
  worker:
    build:
      context: "."
    working_dir: /app/app
    command: celery -A app.worker:celery worker -l INFO
    volumes:
      - .:/app
    depends_on: 
       - "redis"

